name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - release

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: gha-rs
    steps:
      # Must come before Checkout, otherwise goreleaser fails
      - name: Provide GPG and Git
        run: sudo apt update && sudo apt -qq -y install gnupg git curl zip unzip tar bzip2 make

      # Must come after git executable is provided
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # Necessary to run these outside of goreleaser, otherwise
      # /home/runner/_work/holos/holos/internal/frontend/node_modules/.bin/protoc-gen-connect-query is not in PATH
      - name: Install Tools
        run: |
          set -x
          make tools
          make buf
          go generate ./...
          make frontend
          go mod tidy

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_CODE_SIGNING_SECRETKEY }}
          passphrase: ${{ secrets.GPG_CODE_SIGNING_PASSPHRASE }}

      - name: List keys
        run: gpg -K

      - name: Git diff
        run: git diff

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
